version: '3'
services:
  postgres-server:
    container_name: postgres-server
    image: postgres:15.1-alpine
    volumes:
      - /data/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  bot-server:
    container_name: bot-server
    depends_on:
      - postgres-server
    build:
      context: .
      dockerfile: Dockerfile
    image: bot-server:latest
    ports:
      - 5000:5000
    environment:
      - IS_DEPLOYED=${IS_DEPLOYED}
      - APP_URL=${APP_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}